//! A curated 200-word game bank. See README.md for source and difficulty notes.

pub const WORDS_PER_LEVEL: usize = 20;
pub const WINS_TO_ADVANCE: usize = 10;
pub const LEVELS: usize = 10;
const _: () = assert!(WINS_TO_ADVANCE <= WORDS_PER_LEVEL);

// Each group is one approximate difficulty level. The original 100 words were
// checked against brekker23/English-word-frequencies (Apache-2.0); the added
// words are hand-curated for familiar spelling, variety, and Hangman play.
pub const WORDS: &[&str] = &[
    // Level 1
    "HOUSE",
    "WATER",
    "SCHOOL",
    "CHAIR",
    "MOUNTAIN",
    "DOCTOR",
    "CASTLE",
    "SUMMER",
    "WINDOW",
    "FAMILY",
    "BREAD",
    "TREE",
    "RIVER",
    "BEACH",
    "MUSIC",
    "FRIEND",
    "ANIMAL",
    "COFFEE",
    "DINNER",
    "PILLOW",
    // Level 2
    "THUNDER",
    "LANTERN",
    "CANDLE",
    "FOREST",
    "GARDEN",
    "PICTURE",
    "TABLE",
    "ORCHARD",
    "FLOWER",
    "DIAMOND",
    "BASKET",
    "ISLAND",
    "SHADOW",
    "PUMPKIN",
    "TRAIN",
    "CLOSET",
    "BALLOON",
    "TURKEY",
    "MIRROR",
    "PEBBLE",
    // Level 3
    "VILLAGE",
    "BRIDGE",
    "JOURNEY",
    "TURTLE",
    "ORANGE",
    "WHISPER",
    "CAMERA",
    "LIBRARY",
    "CRYSTAL",
    "KITCHEN",
    "BREEZE",
    "CAPTAIN",
    "WAGON",
    "WHISTLE",
    "MEADOW",
    "HAMMER",
    "LADDER",
    "ROCKET",
    "HARBOR",
    "SANDWICH",
    // Level 4
    "GLACIER",
    "ELEPHANT",
    "POCKET",
    "BUTTER",
    "BOTTLE",
    "PLANET",
    "PENCIL",
    "COMPASS",
    "MARKET",
    "TELESCOPE",
    "FOSSIL",
    "ANCHOR",
    "GOBLET",
    "VELVET",
    "DESERT",
    "MONSTER",
    "SATELLITE",
    "HAMSTER",
    "PHANTOM",
    "DRAGON",
    // Level 5
    "YACHT",
    "HARVEST",
    "LABYRINTH",
    "PYRAMID",
    "RHYTHM",
    "APPLE",
    "RAINBOW",
    "MNEMONIC",
    "ASTRONAUT",
    "RABBIT",
    "TORNADO",
    "JASMINE",
    "GIRAFFE",
    "FALCON",
    "TREASURE",
    "RIDDLE",
    "ORBIT",
    "MARBLE",
    "TROPICAL",
    "DOLPHIN",
    // Level 6
    "SAPPHIRE",
    "MARIGOLD",
    "FLAMINGO",
    "IVORY",
    "PARACHUTE",
    "BICYCLE",
    "WHISKEY",
    "MANGO",
    "ABYSS",
    "OXYGEN",
    "EMERALD",
    "CYPRESS",
    "PELICAN",
    "HIBISCUS",
    "CANYON",
    "MIRAGE",
    "TANGERINE",
    "SKELETON",
    "CRIMSON",
    "CHIMERA",
    // Level 7
    "HORIZON",
    "BUCCANEER",
    "NOTEBOOK",
    "OCTOPUS",
    "VULTURE",
    "SUBWAY",
    "PLATYPUS",
    "GLYPH",
    "KANGAROO",
    "BANANA",
    "AVOCADO",
    "BISCUIT",
    "RAVEN",
    "PENGUIN",
    "JAVELIN",
    "COBALT",
    "GARGOYLE",
    "BUNGALOW",
    "AQUARIUM",
    "MONSOON",
    // Level 8
    "QUICKSAND",
    "BOUQUET",
    "MOSQUITO",
    "VORTEX",
    "QUARTZ",
    "CROQUET",
    "WIZARD",
    "SPHINX",
    "FJORD",
    "QUILT",
    "ALCHEMY",
    "KRYPTON",
    "MARQUIS",
    "SQUEEZE",
    "WALTZ",
    "WHIZZ",
    "OASIS",
    "QUIVER",
    "ZIRCON",
    "FUCHSIA",
    // Level 9
    "JACKPOT",
    "QUIZZICAL",
    "QUORUM",
    "JIGSAW",
    "XYLOPHONE",
    "ZIGZAG",
    "ZODIAC",
    "KAYAK",
    "ONYX",
    "ZEPHYR",
    "JUBILEE",
    "JOCKEY",
    "PUZZLE",
    "VIXEN",
    "VIZIER",
    "EXODUS",
    "BLIZZARD",
    "JAGUAR",
    "HAZELNUT",
    "QUACK",
    // Level 10
    "BUZZARD",
    "SQUAWK",
    "JUXTAPOSE",
    "JUKEBOX",
    "GAZELLE",
    "ESPRESSO",
    "PIXIE",
    "JINX",
    "JAZZ",
    "ZUCCHINI",
    "ZOMBIE",
    "PIZZAZZ",
    "JAZZY",
    "FUZZY",
    "OXYMORON",
    "JACKAL",
    "ZIGGURAT",
    "QUIXOTIC",
    "ZEPPELIN",
    "JAWBREAKER",
];

pub fn words_for_level(level: usize) -> &'static [&'static str] {
    let start = level.min(LEVELS - 1) * WORDS_PER_LEVEL;
    &WORDS[start..start + WORDS_PER_LEVEL]
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn bank_has_two_hundred_distinct_playable_words() {
        assert_eq!(WORDS.len(), LEVELS * WORDS_PER_LEVEL);
        assert_eq!(WORDS.len(), 200);
        assert_eq!(
            WORDS.iter().copied().collect::<HashSet<_>>().len(),
            WORDS.len()
        );
        assert!(WORDS.iter().all(|word| {
            (4..=11).contains(&word.len()) && word.bytes().all(|letter| letter.is_ascii_uppercase())
        }));
        for level in 0..LEVELS {
            assert_eq!(words_for_level(level).len(), WORDS_PER_LEVEL);
        }
    }
}
